In [4]:
import numpy as np

In [2]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
#get diminsion
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#get shape
b.shape

(2, 3)

In [10]:
#get type
a.dtype

dtype('int32')

In [11]:
#get size
a.itemsize

4

In [12]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
#get a specific element [row,column]
a[1,5]

13

In [14]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
#get a specific column
a[:,2]

array([ 3, 10])

In [19]:
#getting a [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [20]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
#all 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [22]:
#all other number matrix
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [23]:
#random decimal number
np.random.rand(4,2)

array([[0.64365229, 0.67069892],
       [0.95894451, 0.98594743],
       [0.15443437, 0.96305747],
       [0.76055197, 0.69943034]])

In [25]:
#random integer values
np.random.randint(2,8, size=(3,3))

array([[4, 7, 5],
       [6, 4, 3],
       [4, 4, 5]])

In [3]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
#repeat an array
arr=np.array([[1,2,3]])
rl=np.repeat(arr,3, axis=0)
rl

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [21]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1]= 9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
# becarful when copying arrays, copy function 
a=np.array([1,2,3])
b=a.copy()
b[0]= 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [25]:
#mathematics
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [26]:
a+2

array([3, 4, 5, 6])

In [27]:
a-2

array([-1,  0,  1,  2])

In [28]:
a*2

array([2, 4, 6, 8])

In [29]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [30]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [31]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

# linear algebra

In [3]:
a= np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [7]:
#statistics

In [8]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [9]:
np.min(stats)

1

In [13]:
#here it shows maximum value and axis 1 shows max value in both sets

In [14]:
np.max(stats, axis=1)

array([3, 6])

In [17]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [25]:
# rearranging the arrays

before= np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [1]:
#vertically stacking vectors

In [5]:
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# horizontal stack

In [7]:
h1= np.array([1,2,3,4])
h2= np.array([5,6,7,8])

np.hstack([h1,h2])

array([1, 2, 3, 4, 5, 6, 7, 8])